#!/bin/bash

targetpath=~/
function restore_deep()
{
	restore_shallow
}

function restore_shallow()
{
	cp .gitconfig $targetpath
	cp .gdbinit $targetpath
	cp .vimrc $targetpath
	cp .screenrc $targetpath
	cp .tmux.conf $targetpath

    cp .bash_profile $targetpath
	echo "export CFGROOT=/home/wy" >> $targetpath/.bashrc
	echo "source \$CFGROOT/private/bash_profile" >> $targetpath/.bashrc
	echo "export USER=wy" >> $targetpath/.bashrc

	mkdir $targetpath/.cgdb && cp cgdbrc $targetpath/.cgdb/

	cp .ctags $targetpath
}

if [ $# = 0 ]; then
	restore_shallow

    # Take new config effective
    source ~/.bashrc

    # install vundle
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

	# plugin
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

	# color scheme
    git clone git@github.com:egel/tmux-gruvbox.git

    # pg formatter
    git clone git@github.com:darold/pgFormatter.git

	unzip -d ~/.vim taglist_46.zip

	# node graph, depend on graphviz
	#git clone git@github.com:japinli/pg_node2graph.git

	# nvim
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
	nvm install v16.20.0

	#bear
	#git clone git@github.com:rizsotto/Bear.git

    # if autodie.pm is missing, install it
    # wget https://cpan.metacpan.org/authors/id/T/TO/TODDR/autodie-2.34.tar.gz
	exit 0
fi
