#!/bin/bash

targetpath=~/
function restore_deep()
{
	restore_shallow
}

function restore_shallow()
{
	cp .gitconfig $targetpath
	cp .gdbinit $targetpath	
	cp .vimrc $targetpath	
	cp .screenrc $targetpath	
	cp .tmux.conf $targetpath	
    cp .bash_profile $targetpath	
	echo "export CFGROOT=/home/wy" >> $targetpath/.bashrc
	echo "export USER=wy" >> $targetpath/.bashrc
	echo "source $CFGROOT/private/bash_profile" >> $targetpath/.bashrc
	cp .ctags $targetpath
}

if [ $# = 0 ]; then
	restore_shallow

    # Take new config effective
    source ~/.bash_profile

    # install vundle
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

    git clone git@github.com:egel/tmux-gruvbox.git

    # pg formatter
    git clone git@github.com:darold/pgFormatter.git

    # if autodie.pm is missing, install it
    # wget https://cpan.metacpan.org/authors/id/T/TO/TODDR/autodie-2.34.tar.gz
	exit 0
fi
