#!/bin/bash
if [ $# -eq 0 ]; then
    ps -ef|grep postgres|grep $USER
fi

if [ "$1" == "-i" ]; then
    ps -ef|grep postgres|grep $USER|grep idle | grep seg
fi

if [ "$1" == "-d" ]; then
    ps -ef|grep postgres|grep $USER|grep idle | local|grep -v seg
fi
