FROM centos9-server:v1

RUN sudo yum install -y texinfo bear gdb bpftrace cscope ctags

RUN echo ". /usr/share/bash-completion/completions/git" >> ~/.bash_profile

RUN mkdir /home/wy/.cargo
COPY ./config.toml /home/wy/.cargo/
RUN source ~/.bash_profile && \
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

RUN mkdir -p /home/wy/.config/nvim/lua/config && \
	mkdir -p /home/wy/.config/nvim/lua/plugins
COPY nvim/options.lua /home/wy/.config/nvim/lua/config/
COPY nvim/basic.lua /home/wy/.config/nvim/lua/plugins/
COPY nvim/init.lua /home/wy/.config/nvim/


#RUN sudo dnf search geos-devel

COPY install_dev_from_git.sh /install_dev_from_git.sh
RUN sh /install_dev_from_git.sh

COPY pg_dev_dependency.sh /pg_dev_dependency.sh
RUN sudo sh /pg_dev_dependency.sh
