# This docker decribe running server and system utility, without developement
# Toolkits
FROM rockylinux/rockylinux:9-ubi-init

RUN yum install -y wget

RUN wget https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/e/epel-release-9-10.el9.noarch.rpm && \
	rpm -Uvh epel-release-9-10.el9.noarch.rpm && \
	rm -f epel-release-9-10.el9.noarch.rpm

RUN dnf install -y 'dnf-command(config-manager)' && \
	dnf config-manager --enable crb

RUN yum install -y --allowerasing sudo tmux shadow passwd git cpio clangd vim \
	cmake curl zip unzip tar wget man binutils  jq net-tools nmap iputils \
	rpm-build rpmdevtools lz4 zstd tree man-pages cloc

RUN yum install -y sysstat dstat perf htop atop

# net perf, including netstat, uperf && perftest for IB/RDMA
RUN yum install -y iperf nmon tcpdump iproute 

# disk perf; including iostat
RUN yum install -y blktrace lsof

# iotop can't be used in docker for absent docker support of netlink component
# RUN sudo yum install -y iotop

# CPU, including pidstat, lscpu, pstree(psmisc)
RUN yum install -y perf psmisc cpuid

# Memory, including vmstat, free, pmap,
RUN yum install -y smem

RUN yum install -y fio

RUN yum install -y strace 

# other tools
RUN yum install -y dmidecode

RUN useradd -m -u 1000 wy && \
	usermod -G wheel wy && \
	echo 'wy ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/wy

RUN mkdir -p /home/wy/.ssh
COPY ssh/id_rsa /home/wy/.ssh/
COPY ssh/authorized_keys /home/wy/.ssh/
RUN chmod 600 /home/wy/.ssh/id_rsa && \
    chmod 600 /home/wy/.ssh/authorized_keys && \
    echo "StrictHostKeyChecking no" >> /home/wy/.ssh/config && \
    chmod 600 /home/wy/.ssh/config && \
    chown -R wy:wy /home/wy/.ssh

USER wy

COPY ./install_from_git.sh /install_from_git.sh
RUN sh /install_from_git.sh

RUN curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
RUN echo "source /home/wy/private/vimrc" > /home/wy/.vimrc
RUN sed -i "/colorscheme gruvbox/d" /home/wy/private/vimrc

RUN vim -c "PluginInstall" -c "qa!"
RUN vim -c "PlugInstall" -c "qa!"

RUN echo "export RUSTUP_DIST_SERVER=\"https://rsproxy.cn\"" >> ~/.bash_profile
RUN echo "export RUSTUP_UPDATE_ROOT=\"https://rsproxy.cn/rustup\"" >> ~/.bash_profile
RUN echo "alias ls='ls --color=auto'" >> ~/.bash_profile
RUN echo "alias ll='ls -l'" >> ~/.bash_profile
